### ISSUE TITLE
Collab for EDU chain project

### ISSUE THREAD

**Issue by jilt** [Webmoss/grasp#1]
Hello, I was pointed to you by Megan Miao to discuss some ideas I have for an educational portal with gamification and peculiar incentives, please let me know if you're interested!

**Comment by jilt** [comment]
[This](https://www.figma.com/design/torRFLTfErpWV6hSS8CZks/Educhain?node-id=102-227&t=Q2fzCdovdEcAwCtP-0) is the basic UI I have shown to Megan There's more to the incentive part but it's all built up with tailwind components:

**Comment by Webmoss** [comment]
Hi Laura, hope you keeping well today.

Feel free to reach out to me at craigmoss36@gmail.com and let's setup a google meet or zoom and we can chat through your idea and we can go from there. 

Regards
Craig
